# see https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-codebuild-devicefarm.html
version: 0.2

env:
  variables:
    LITTLE_INTERACTIVE: "false"
  parameter-store:
    NPM_TOKEN: "/aws/reference/secretsmanager/applications/cicd/cell0/dev/npmjs-token"
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Entered the install phase - jq already installed ..."
      - |
        (
          if ! which hugo > /dev/null 2>&1; then
            cd /tmp
            wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-64bit.deb
            dpkg --install hugo.deb
          fi
        )
      #- apt-get update -y
      #- apt-get install -y jq
  pre_build:
    commands:
      # see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html
      # see https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
      - echo "HOME is $HOME, CODEBUILD_SRC_DIR is $CODEBUILD_SRC_DIR, CODEBUILD_SRC_DIR_HELPERS is $CODEBUILD_SRC_DIR_HELPERS, pwd is $(pwd), region is $AWS_REGION"
      - echo "//registry.npmjs.org/:_authToken=$(echo "$NPM_TOKEN" | jq -e -r .token)" > "$HOME/.npmrc"
      - mkdir -p "$HOME/.aws"; /bin/echo -e "[default]\nregion = ${AWS_REGION}\noutput = json\ncredential_source = Ec2InstanceMetadata\n" | tee "$HOME/.aws/config"
      - npm ci
      - pip install yq --upgrade
  build:
    commands:
      # stage sets up ./dist folder
      - npm run stage
      - npm run lint
      - npm audit --production --audit-level=high
      - npm run test
      - (cd hugo-site/hugo-apps.frickjack.com && hugo)
      - test -d hugo-site/hugo-apps.frickjack.com/public
  post_build:
    commands:
      - echo "CODEBUILD_WEBHOOK_TRIGGER == $CODEBUILD_WEBHOOK_TRIGGER"
      - BUILD_TYPE="$(echo $CODEBUILD_WEBHOOK_TRIGGER | awk -F / '{ print $1 }')"
      - echo "BUILD_TYPE is $BUILD_TYPE"
      # publish on tag events - see https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
      - if test "$BUILD_TYPE" = "tag"; then bash "$CODEBUILD_SRC_DIR_HELPERS/AWS/little.sh" s3web publish ./hugo-site/hugo-apps.frickjack.com/public s3://027326493842-apps-frickjack-20210609; fi
